FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /src

RUN apt-get update && apt-get install -y default-jdk

COPY requirements.txt ./
COPY api api
COPY ai ai
COPY bs.py ./

RUN pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]